name: ci

on:
  push:
    branches:
    - master

jobs:
    build:
    runs-on: ununtu-latest
    steps:
    - name: Check out code 
   - uses: actions/checkout@v2 
    - name: Setup ,Net 3.1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
       run: dotnet restore
    - name: Build app
       run: dotnet build -c Release --no-restore
